runtime: python
env: flex
entrypoint: streamlit run main.py --server.port $PORT

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 25

network:
  session_affinity: true

