name: Deploy to App Engine

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with google cloud
        uses: google-github-actions/auth@v2
        with:
            service_account: sudarshan-github@tuberculosis-443609.iam.gserviceaccount.com
            project_id: tuberculosis-443609
            credentials_json: ${{ secrets.TUBERCULOSIS_JSON }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tuberculosis-443609
      - name: Deploy to App Engine
        run: gcloud app deploy --project tuberculosis-443609 --service-account sudarshan-github@tuberculosis-443609.iam.gserviceaccount.com


